//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CBR.Web.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;tabCapitalPlanDashboard&quot; class=&quot;tab-pane fade in active col-sm-8&quot;&gt;
        ///    &lt;div class=&quot;panel-body&quot;&gt;
        ///        &lt;div class=&quot;row&quot;&gt;
        ///            &lt;div class=&quot;col-sm-6 col-sm-offset-0 col-md-12 col-md-offset-0&quot;&gt;
        ///                &lt;h2&gt;WELCOME&lt;/h2&gt;
        ///                &lt;p&gt;You have arrived at your Capital Plan Project portal.  CB Resource, Inc. is committed to providing a quality product and customer experience.  Please review the following information.&lt;/p&gt;
        ///                &lt;hr /&gt;
        ///
        ///                &lt;h3&gt;OVERVIEW&lt;/h3 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CapitalPlan {
            get {
                return ResourceManager.GetString("CapitalPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;tabComplianceDashboard&quot; class=&quot;tab-pane fade in active col-sm-8&quot;&gt;
        ///    &lt;div class=&quot;panel-body&quot;&gt;
        ///        &lt;div class=&quot;row&quot;&gt;
        ///            &lt;div class=&quot;col-sm-6 col-sm-offset-0 col-md-12 col-md-offset-0&quot;&gt;
        ///                &lt;h2&gt;WELCOME&lt;/h2&gt;
        ///                &lt;p&gt;You have arrived at your Compliance Project portal.  CB Resource, Inc. is committed to providing a quality product and customer experience.  Please review the following information.&lt;/p&gt;
        ///                &lt;hr /&gt;
        ///
        ///                &lt;h3&gt;OVERVIEW&lt;/h3&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Compliance {
            get {
                return ResourceManager.GetString("Compliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;tabCreditDashboard&quot; class=&quot;tab-pane fade in active col-sm-8&quot;&gt;
        ///    &lt;div class=&quot;panel-body&quot;&gt;
        ///        &lt;div class=&quot;row&quot;&gt;
        ///            &lt;div class=&quot;col-sm-6 col-sm-offset-0 col-md-12 col-md-offset-0&quot;&gt;
        ///                &lt;h2&gt;WELCOME&lt;/h2&gt;
        ///                &lt;p&gt;You have arrived at your Credit Project portal.  CB Resource, Inc. is committed to providing a quality product and customer experience.  Please review the following information.&lt;/p&gt;
        ///                &lt;hr /&gt;
        ///
        ///                &lt;h3&gt;OVERVIEW&lt;/h3&gt;
        ///
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;tabDeNovoDashboard&quot; class=&quot;tab-pane fade in active col-sm-8&quot;&gt;
        ///    &lt;div class=&quot;panel-body&quot;&gt;
        ///        &lt;div class=&quot;row&quot;&gt;
        ///            &lt;div class=&quot;col-sm-6 col-sm-offset-0 col-md-12 col-md-offset-0&quot;&gt;
        ///                &lt;h2&gt;WELCOME&lt;/h2&gt;
        ///                &lt;p&gt;You have arrived at your DeNovo Project portal.  CB Resource, Inc. is committed to providing a quality product and customer experience.  Please review the following information.&lt;/p&gt;
        ///                &lt;hr /&gt;
        ///
        ///                &lt;h3&gt;OVERVIEW&lt;/h3&gt;
        ///
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DeNovo {
            get {
                return ResourceManager.GetString("DeNovo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;tabERADashboard&quot; class=&quot;tab-pane fade in active col-sm-8&quot;&gt;
        ///    &lt;div class=&quot;panel-body&quot;&gt;
        ///        &lt;div class=&quot;row&quot;&gt;
        ///            &lt;div class=&quot;col-sm-6 col-sm-offset-0 col-md-12 col-md-offset-0&quot;&gt;
        ///                &lt;h2&gt;WELCOME&lt;/h2&gt;
        ///                &lt;p&gt;You have arrived at your ERA Project portal.  CB Resource, Inc. is committed to providing a quality product and customer experience.  Please review the following information.&lt;/p&gt;
        ///                &lt;hr /&gt;
        ///                
        ///                &lt;h3&gt;OVERVIEW&lt;/h3&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ERA {
            get {
                return ResourceManager.GetString("ERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;tabERMDashboard&quot; class=&quot;tab-pane fade in active col-sm-8&quot;&gt;
        ///    &lt;div class=&quot;panel-body&quot;&gt;
        ///        &lt;div class=&quot;row&quot;&gt;
        ///            &lt;div class=&quot;col-sm-6 col-sm-offset-0 col-md-12 col-md-offset-0&quot;&gt;
        ///                &lt;h2&gt;WELCOME&lt;/h2&gt;
        ///                &lt;p&gt;You have arrived at your Enterprise Risk Management (&quot;ERM&quot;) Project portal. CB Resource, Inc. is committed to providing a quality product and customer experience. Please review the following information.&lt;/p&gt;
        ///                &lt;hr /&gt;
        ///
        ///                &lt;h3&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ERM {
            get {
                return ResourceManager.GetString("ERM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;tabM&amp;ADashboard&quot; class=&quot;tab-pane fade in active col-sm-8&quot;&gt;
        ///    &lt;div class=&quot;panel-body&quot;&gt;
        ///        &lt;div class=&quot;row&quot;&gt;
        ///            &lt;div class=&quot;col-sm-6 col-sm-offset-0 col-md-12 col-md-offset-0&quot;&gt;
        ///                &lt;h2&gt;WELCOME&lt;/h2&gt;
        ///                &lt;p&gt;You have arrived at your M&amp;A Project portal.  CB Resource, Inc. is committed to providing a quality product and customer experience.  Please review the following information.&lt;/p&gt;
        ///                &lt;hr /&gt;
        ///
        ///                &lt;h3&gt;OVERVIEW&lt;/h3&gt;
        ///
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MA {
            get {
                return ResourceManager.GetString("MA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;tabStrategyDashboard&quot; class=&quot;tab-pane fade in active col-sm-8&quot;&gt;
        ///    &lt;div class=&quot;panel-body&quot;&gt;
        ///        &lt;div class=&quot;row&quot;&gt;
        ///            &lt;div class=&quot;col-sm-6 col-sm-offset-0 col-md-12 col-md-offset-0&quot;&gt;
        ///                &lt;h2&gt;WELCOME&lt;/h2&gt;
        ///                &lt;p&gt;You have arrived at your Strategic Plan Project portal. CB Resource, Inc. is committed to providing a quality product and customer experience. Please review the following information.&lt;/p&gt;
        ///                &lt;hr /&gt;
        ///
        ///                &lt;h3&gt;OVERVIEW&lt;/h3&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Strategy {
            get {
                return ResourceManager.GetString("Strategy", resourceCulture);
            }
        }
    }
}
