//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveCallReportList
    {
        public string ReportingPeriod { get; set; }
        public Nullable<int> CertNumber { get; set; }
        public string InstitutionName { get; set; }
        public System.DateTime DateInserted { get; set; }
    }
}
