//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppAccessControl
    {
        public int AccessControlKey { get; set; }
        public long TenantKey { get; set; }
        public bool IsAccessible { get; set; }
        public int ModuleKey { get; set; }
    
        public virtual AppTenant AppTenant { get; set; }
        public virtual AppModule AppModule { get; set; }
    }
}
