//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppCRAMRiskRating
    {
        public long ModelKey { get; set; }
        public Nullable<decimal> Low { get; set; }
        public Nullable<decimal> LowModerate { get; set; }
        public Nullable<decimal> Moderate { get; set; }
        public Nullable<decimal> ModerateHigh { get; set; }
        public Nullable<decimal> High { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
