//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppCRAMRiskCategory
    {
        public long ModelKey { get; set; }
        public Nullable<short> CreditRiskScore { get; set; }
        public Nullable<decimal> CreditRiskWeighing { get; set; }
        public Nullable<short> InterestRateRiskScore { get; set; }
        public Nullable<decimal> InterestRateRiskWeighing { get; set; }
        public Nullable<short> LiquidityRiskScore { get; set; }
        public Nullable<decimal> LiquidityRiskWeighing { get; set; }
        public Nullable<short> OperationalRiskScore { get; set; }
        public Nullable<decimal> OperationalRiskWeighing { get; set; }
        public Nullable<short> ComplianceRiskScore { get; set; }
        public Nullable<decimal> ComplianceRiskWeighing { get; set; }
        public Nullable<short> StrategicRiskScore { get; set; }
        public Nullable<decimal> StrategicRiskWeighing { get; set; }
        public Nullable<short> ReputationRiskScore { get; set; }
        public Nullable<decimal> ReputationRiskWeighing { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
