//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppCDOrder
    {
        public int OrderKey { get; set; }
        public string OrderDate { get; set; }
        public Nullable<int> InstitutionKey { get; set; }
        public string OrderedBy { get; set; }
        public string ContactPhone { get; set; }
        public string Term { get; set; }
        public string Callable { get; set; }
        public string CallFrequency { get; set; }
        public string Rate { get; set; }
        public string Amount { get; set; }
        public string SettleDate { get; set; }
        public string InterestPaymentFrequency { get; set; }
        public string Status { get; set; }
        public System.DateTime AuditInsertedDateTime { get; set; }
        public System.DateTime AuditUpdatedDateTime { get; set; }
        public string Notes { get; set; }
    }
}
