//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppCRAMAdjustBankData
    {
        public long ModelKey { get; set; }
        public Nullable<decimal> Tier1LeverageRatio { get; set; }
        public Nullable<decimal> CET1CapitalRatio { get; set; }
        public Nullable<decimal> Tier1CapitalRatio { get; set; }
        public Nullable<decimal> TotalCapitalRatio { get; set; }
        public Nullable<decimal> CommonEquityTier1Capital { get; set; }
        public Nullable<decimal> Tier1Capital { get; set; }
        public Nullable<decimal> TotalCapital { get; set; }
        public Nullable<decimal> TotalAssetsLeveragePurposes { get; set; }
        public Nullable<decimal> TotalRiskWeightedAssets { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
