//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppFavoriteSearch
    {
        public int FavoriteSearchKey { get; set; }
        public long UserKey { get; set; }
        public string Location { get; set; }
        public string AssetSize { get; set; }
        public string Percentile { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
