//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppFavoriteBank
    {
        public int FavoriteBankKey { get; set; }
        public long UserKey { get; set; }
        public int InstitutionKey { get; set; }
        public bool IsDefaultBank { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual DimInstitution DimInstitution { get; set; }
    }
}
