//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppInfoCenterImage
    {
        public int ImageKey { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public Nullable<System.DateTime> AuditInsertedDateTime { get; set; }
    }
}
