//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppManageCDRate
    {
        public int TermKey { get; set; }
        public string Term { get; set; }
        public string FixedRate { get; set; }
        public string Callable { get; set; }
        public System.DateTime AuditInsertedDateTime { get; set; }
        public System.DateTime AuditUpdatedDateTime { get; set; }
    }
}
