//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppStrategicForecastInputData
    {
        public long TenantKey { get; set; }
        public long UserKey { get; set; }
        public int ScenarioKey { get; set; }
        public short MetricKey { get; set; }
        public Nullable<decimal> Year0 { get; set; }
        public Nullable<decimal> Year1 { get; set; }
        public Nullable<decimal> Year2 { get; set; }
        public Nullable<decimal> Year3 { get; set; }
        public Nullable<decimal> Year4 { get; set; }
        public Nullable<decimal> Year5 { get; set; }
        public Nullable<System.DateTime> AuditInsertedDate { get; set; }
        public Nullable<decimal> PriorYear { get; set; }
        public Nullable<decimal> CurrentYearYTD { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual AppStrategicForecastInputMetric AppStrategicForecastInputMetric { get; set; }
        public virtual AppStrategicForecastScenario AppStrategicForecastScenario { get; set; }
        public virtual AppUser AppUser { get; set; }
        public virtual AppTenant AppTenant { get; set; }
    }
}
