//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppStrategicForecastInputMetric
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppStrategicForecastInputMetric()
        {
            this.AppStrategicForecastInputDatas = new HashSet<AppStrategicForecastInputData>();
        }
    
        public short MetricKey { get; set; }
        public string MetricName { get; set; }
        public Nullable<System.DateTime> AuditInsertedDate { get; set; }
        public string UBPRConceptCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppStrategicForecastInputData> AppStrategicForecastInputDatas { get; set; }
    }
}
