//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppStrategicForecastSummary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppStrategicForecastSummary()
        {
            this.AppStrategicForecastSummaryScenarios = new HashSet<AppStrategicForecastSummaryScenario>();
        }
    
        public int SummaryKey { get; set; }
        public string SummaryName { get; set; }
        public long TenantKey { get; set; }
        public long UserKey { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> AuditInsertedDate { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppStrategicForecastSummaryScenario> AppStrategicForecastSummaryScenarios { get; set; }
        public virtual AppTenant AppTenant { get; set; }
    }
}
