//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppUser()
        {
            this.AppUserClaims = new HashSet<AppUserClaim>();
            this.AppUserLogins = new HashSet<AppUserLogin>();
            this.DimCustPeerGroups = new HashSet<DimCustPeerGroup>();
            this.AppFavoriteBanks = new HashSet<AppFavoriteBank>();
            this.AppFavoriteSearches = new HashSet<AppFavoriteSearch>();
            this.AppUserRoles = new HashSet<AppUserRole>();
            this.AppStrategicForecastScenarios = new HashSet<AppStrategicForecastScenario>();
            this.AppStrategicForecastSummaries = new HashSet<AppStrategicForecastSummary>();
            this.AppStrategicForecastInputDatas = new HashSet<AppStrategicForecastInputData>();
            this.AppStrategicForecastSummaryScenarios = new HashSet<AppStrategicForecastSummaryScenario>();
            this.FactUBPRBenchmarks = new HashSet<FactUBPRBenchmark>();
            this.FactUBPRBenchmarkThresholds = new HashSet<FactUBPRBenchmarkThreshold>();
            this.RptCBRRiskRadarUserMetricmappings = new HashSet<RptCBRRiskRadarUserMetricmapping>();
        }
    
        public long UserKey { get; set; }
        public long TenantKey { get; set; }
        public string Login { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string Department { get; set; }
        public string EMail { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public bool IsLocked { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
        public string ActivationToken { get; set; }
        public bool EmailConfirmed { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> HasAcceptedTerms { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public Nullable<bool> IsPasswordReset { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppUserClaim> AppUserClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppUserLogin> AppUserLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimCustPeerGroup> DimCustPeerGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppFavoriteBank> AppFavoriteBanks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppFavoriteSearch> AppFavoriteSearches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppUserRole> AppUserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppStrategicForecastScenario> AppStrategicForecastScenarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppStrategicForecastSummary> AppStrategicForecastSummaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppStrategicForecastInputData> AppStrategicForecastInputDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppStrategicForecastSummaryScenario> AppStrategicForecastSummaryScenarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactUBPRBenchmark> FactUBPRBenchmarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactUBPRBenchmarkThreshold> FactUBPRBenchmarkThresholds { get; set; }
        public virtual AppTenant AppTenant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RptCBRRiskRadarUserMetricmapping> RptCBRRiskRadarUserMetricmappings { get; set; }
    }
}
