//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserRole
    {
        public long UserKey { get; set; }
        public long RoleKey { get; set; }
        public int UserRoleKey { get; set; }
        public bool IsAccessible { get; set; }
    
        public virtual AppRole AppRole { get; set; }
        public virtual AppUser AppUser { get; set; }
    }
}
