//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataRefreshError
    {
        public int Id { get; set; }
        public Nullable<System.Guid> DataRefreshGUID { get; set; }
        public string QuarterDate { get; set; }
        public string ErrorAtStep { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public Nullable<bool> IsErrorSolved { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
    }
}
