//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataRefreshTimePeriod
    {
        public int PeriodId { get; set; }
        public string QuarterName { get; set; }
        public string QuarterYear { get; set; }
        public string QuarterDate { get; set; }
        public Nullable<bool> IsProcessStarted { get; set; }
        public Nullable<bool> IsProcessCompleted { get; set; }
        public Nullable<bool> IsCallDataFilesDownloaded { get; set; }
        public Nullable<System.DateTime> AuditInsertDate { get; set; }
        public Nullable<bool> IsQuarternameEnvVarUpdated { get; set; }
        public Nullable<bool> IsStatFilesDownloaded { get; set; }
        public Nullable<bool> IsStdGrpInstFilesDownloaded { get; set; }
        public Nullable<bool> IsInstFilesDownloaded { get; set; }
        public Nullable<bool> IsCallDataFilesStarted { get; set; }
        public Nullable<System.Guid> DataRefreshGUId { get; set; }
        public Nullable<bool> IsStdGrpInstFilesStarted { get; set; }
        public Nullable<int> NoOfRetries { get; set; }
        public Nullable<bool> IsProdProcessStarted { get; set; }
        public Nullable<bool> IsProdProcessCompleted { get; set; }
        public Nullable<bool> isManualActionRequired { get; set; }
        public bool isTimePeriodFilesAvailable { get; set; }
        public bool isNewQuarter { get; set; }
        public Nullable<bool> IsCertDownloadStarted { get; set; }
        public Nullable<bool> IsCertDownloadCompleted { get; set; }
        public bool IsSecondRefreshRequired { get; set; }
    }
}
