//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataRefreshUpdate
    {
        public int DataRefreshId { get; set; }
        public Nullable<System.Guid> DataRefreshGUID { get; set; }
        public string CERTNOS { get; set; }
        public Nullable<bool> isUpdateRequired { get; set; }
        public string QuarterDate { get; set; }
        public Nullable<System.DateTime> DataRefreshedDate { get; set; }
        public Nullable<bool> isUBPRDataFilesjobCompleted { get; set; }
        public Nullable<bool> isStgUBPRStandardPeerGroupPerBankDownloaded { get; set; }
        public Nullable<bool> isStdGroupPerBankFileAvailable { get; set; }
        public Nullable<bool> isStatDataFilesDownloaded { get; set; }
        public Nullable<bool> isStgDataLoadJobStep4Completed { get; set; }
        public Nullable<bool> isStgDataLoadJobStep9Completed { get; set; }
        public Nullable<bool> isCBRDataWarehouseDataLoad13Completed { get; set; }
        public Nullable<bool> isCBRDataWarehouseDataLoad23Completed { get; set; }
        public Nullable<bool> isCBRDataWarehouseDataLoad24Completed { get; set; }
        public Nullable<bool> isCBRDataWarehouseDataLoad25Completed { get; set; }
        public Nullable<bool> isErrorOccured { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public Nullable<bool> isStgDataLoadJobStep5Completed { get; set; }
        public Nullable<bool> isStgDataLoadJobStep6Completed { get; set; }
        public bool isNewQuarter { get; set; }
        public Nullable<System.DateTime> LastCallDataDownloadedDate { get; set; }
    }
}
