//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimDate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimDate()
        {
            this.FactCustPGUBPRDatas = new HashSet<FactCustPGUBPRData>();
            this.FactStdPGUBPRDatas = new HashSet<FactStdPGUBPRData>();
        }
    
        public int DateKey { get; set; }
        public System.DateTime FullDate { get; set; }
        public byte DayNumberOfWeek { get; set; }
        public string DayNameOfWeek { get; set; }
        public string WeekDayType { get; set; }
        public byte DayNumberOfMonth { get; set; }
        public short DayNumberOfYear { get; set; }
        public byte WeekNumberOfYear { get; set; }
        public string MonthNameOfYear { get; set; }
        public byte MonthNumberOfYear { get; set; }
        public byte QuarterNumberCalendar { get; set; }
        public string QuarterNameCalendar { get; set; }
        public byte SemesterNumberCalendar { get; set; }
        public string SemesterNameCalendar { get; set; }
        public short YearCalendar { get; set; }
        public byte MonthNumberFiscal { get; set; }
        public byte QuarterNumberFiscal { get; set; }
        public string QuarterNameFiscal { get; set; }
        public byte SemesterNumberFiscal { get; set; }
        public string SemesterNameFiscal { get; set; }
        public short YearFiscal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactCustPGUBPRData> FactCustPGUBPRDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactStdPGUBPRData> FactStdPGUBPRDatas { get; set; }
    }
}
