//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimInstitution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimInstitution()
        {
            this.AppFavoriteBanks = new HashSet<AppFavoriteBank>();
            this.DimInstitutionBranches = new HashSet<DimInstitutionBranch>();
            this.FactUBPRBenchmarks = new HashSet<FactUBPRBenchmark>();
            this.FactUBPRBenchmarkThresholds = new HashSet<FactUBPRBenchmarkThreshold>();
            this.DimCustPeerGroupDetails = new HashSet<DimCustPeerGroupDetail>();
            this.AppTenants = new HashSet<AppTenant>();
        }
    
        public int InstitutionKey { get; set; }
        public Nullable<int> CertNumber { get; set; }
        public Nullable<int> Rssd { get; set; }
        public string InstitutionName { get; set; }
        public string InstitutionAddress { get; set; }
        public string InstitutionCity { get; set; }
        public Nullable<decimal> InstitutionZip { get; set; }
        public string InstitutionStateName { get; set; }
        public Nullable<decimal> Docket { get; set; }
        public Nullable<decimal> AssetTotal { get; set; }
        public string BankCharterClass { get; set; }
        public Nullable<decimal> Charter { get; set; }
        public string CharterAgencyName { get; set; }
        public string Conserve { get; set; }
        public Nullable<decimal> MajorAndMinorCategoryCode { get; set; }
        public Nullable<decimal> CmsaNo { get; set; }
        public string Cmsa { get; set; }
        public string County { get; set; }
        public Nullable<decimal> DepositTotal { get; set; }
        public Nullable<decimal> EquityTotal { get; set; }
        public Nullable<System.DateTime> EstablishedDate { get; set; }
        public Nullable<decimal> FDICAssignedRegionOfficeNumber { get; set; }
        public string FDICRegion { get; set; }
        public string FDICSupervisoryRegion { get; set; }
        public Nullable<decimal> FederalReserveDistrict { get; set; }
        public Nullable<decimal> FederalCharter { get; set; }
        public string FDICFieldOffice { get; set; }
        public Nullable<decimal> MetropolitanStatisticalAreaNo { get; set; }
        public string MetropolitanStatisticalArea { get; set; }
        public Nullable<decimal> NewCertNumber { get; set; }
        public Nullable<decimal> Oakar { get; set; }
        public Nullable<decimal> OfficeOfThriftSupervisionDistrict { get; set; }
        public string OfficeOfThriftSupervisionRegion { get; set; }
        public string Regulator { get; set; }
        public Nullable<decimal> StateCharter { get; set; }
        public Nullable<decimal> ReturnOnAsset { get; set; }
        public Nullable<decimal> ReturnOnAssetEquivalency { get; set; }
        public Nullable<decimal> ReturnOnEquity { get; set; }
        public Nullable<decimal> ReturnOnEquityEquivalency { get; set; }
        public string Stalp { get; set; }
        public Nullable<decimal> StateCounty { get; set; }
        public Nullable<decimal> StateNum { get; set; }
        public string WebAddress { get; set; }
        public Nullable<decimal> OfficeOfTheComptrollerDistrict { get; set; }
        public Nullable<decimal> UniqueNumber { get; set; }
        public Nullable<decimal> UltCertNumber { get; set; }
        public Nullable<decimal> NumOfOffices { get; set; }
        public string HeadQuarterCity { get; set; }
        public Nullable<decimal> DomesticDepositsTotal { get; set; }
        public string BankHoldingCompany { get; set; }
        public Nullable<decimal> NetIncomeTotal { get; set; }
        public Nullable<decimal> NetIncomeEquivalency { get; set; }
        public Nullable<decimal> RSSDIDNumber { get; set; }
        public string StalpHcr { get; set; }
        public Nullable<decimal> MultiStateBranches { get; set; }
        public Nullable<decimal> RoapTx { get; set; }
        public Nullable<decimal> RoapTxQ { get; set; }
        public Nullable<bool> IsTrustPowers { get; set; }
        public Nullable<decimal> AssetConcentrationHierarchy { get; set; }
        public string SpecGrpN { get; set; }
        public Nullable<decimal> Tract { get; set; }
        public string Csa { get; set; }
        public Nullable<decimal> CsaNo { get; set; }
        public Nullable<bool> IsCsa { get; set; }
        public string Cbsa { get; set; }
        public Nullable<decimal> CbsaNo { get; set; }
        public string CbsaMetroName { get; set; }
        public Nullable<decimal> CbsaMetro { get; set; }
        public Nullable<bool> IsCbsaMetro { get; set; }
        public string CbsaDiv { get; set; }
        public Nullable<decimal> CbsaDivNo { get; set; }
        public Nullable<bool> IsCbsaDiv { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<System.DateTime> RunDate { get; set; }
        public Nullable<decimal> NumOfDomesticUSOffices { get; set; }
        public Nullable<decimal> NumOfForeignOffices { get; set; }
        public Nullable<decimal> SubchapterSCorporations { get; set; }
        public Nullable<System.DateTime> DepositInsuranceDate { get; set; }
        public Nullable<System.DateTime> LastStructureChangeEffectiveDate { get; set; }
        public Nullable<bool> IsMutualOwnership { get; set; }
        public Nullable<int> ParentCertNumber { get; set; }
        public string InsuranceFundMembership { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime AuditInsertedDateTime { get; set; }
        public int AuditInsertedPackageKey { get; set; }
        public Nullable<System.DateTime> AuditUpdatedDateTime { get; set; }
        public Nullable<int> AuditUpdatedPackageKey { get; set; }
        public byte[] AuditHashMD5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppFavoriteBank> AppFavoriteBanks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimInstitutionBranch> DimInstitutionBranches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactUBPRBenchmark> FactUBPRBenchmarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactUBPRBenchmarkThreshold> FactUBPRBenchmarkThresholds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimCustPeerGroupDetail> DimCustPeerGroupDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppTenant> AppTenants { get; set; }
    }
}
