//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimInstitutionBranch
    {
        public int InstitutionBranchKey { get; set; }
        public int InstitutionBranchId { get; set; }
        public int InstitutionKey { get; set; }
        public string InstitutionBranchName { get; set; }
        public string InstitutionBranchAddress { get; set; }
        public string InstitutionBranchCity { get; set; }
        public string InstitutionBranchZip { get; set; }
        public string InstitutionBranchStateName { get; set; }
        public Nullable<int> CertNumber { get; set; }
        public Nullable<System.DateTime> InstitutionBranchEstablishedDate { get; set; }
        public string InstitutionBranchOfficeName { get; set; }
        public Nullable<decimal> InstitutionBranchOfficeNum { get; set; }
        public Nullable<int> FiUniNum { get; set; }
        public Nullable<bool> IsCbsaMetro { get; set; }
        public Nullable<bool> IsCbsaMicro { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime AuditInsertedDateTime { get; set; }
        public int AuditInsertedPackageKey { get; set; }
        public Nullable<System.DateTime> AuditUpdatedDateTime { get; set; }
        public Nullable<int> AuditUpdatedPackageKey { get; set; }
        public byte[] AuditHashMD5 { get; set; }
    
        public virtual DimInstitution DimInstitution { get; set; }
    }
}
