//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimMDRM
    {
        public int MDRMKey { get; set; }
        public string MDRMNumber { get; set; }
        public string MDRMShortDefinition { get; set; }
        public System.DateTime AuditInsertedDateTime { get; set; }
        public int AuditInsertedPackageKey { get; set; }
        public Nullable<System.DateTime> AuditUpdatedDateTime { get; set; }
        public Nullable<int> AuditUpdatedPackageKey { get; set; }
        public byte[] AuditHashMD5 { get; set; }
        public string CustomMDRMDesc { get; set; }
    }
}
