//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimReportingPeriodType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimReportingPeriodType()
        {
            this.FactCustPGUBPRDatas = new HashSet<FactCustPGUBPRData>();
            this.FactStdPGUBPRDatas = new HashSet<FactStdPGUBPRData>();
            this.FactUBPRBenchmarks = new HashSet<FactUBPRBenchmark>();
        }
    
        public int ReportingPeriodTypeKey { get; set; }
        public string ReportingPeriodType { get; set; }
        public int AuditInsertedPackageKey { get; set; }
        public System.DateTime AuditInsertedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactCustPGUBPRData> FactCustPGUBPRDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactStdPGUBPRData> FactStdPGUBPRDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactUBPRBenchmark> FactUBPRBenchmarks { get; set; }
    }
}
