//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimStdPeerGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimStdPeerGroup()
        {
            this.DimStdPeerGroupDetails = new HashSet<DimStdPeerGroupDetail>();
            this.FactStdPGUBPRDatas = new HashSet<FactStdPGUBPRData>();
        }
    
        public int StdPeerGroupKey { get; set; }
        public string StdPeerGroupCode { get; set; }
        public string StdPeerGroupName { get; set; }
        public System.DateTime AuditInsertedDateTime { get; set; }
        public int AuditInsertedPackageKey { get; set; }
        public Nullable<System.DateTime> AuditUpdatedDateTime { get; set; }
        public Nullable<int> AuditUpdatedPackageKey { get; set; }
        public byte[] AuditHashMD5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimStdPeerGroupDetail> DimStdPeerGroupDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactStdPGUBPRData> FactStdPGUBPRDatas { get; set; }
    }
}
