//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERMAccesscontrol
    {
        public int ERMAccessControlKey { get; set; }
        public Nullable<int> TenantKey { get; set; }
        public string TenantType { get; set; }
        public Nullable<int> institutionkey { get; set; }
        public string Institutionname { get; set; }
        public Nullable<int> userkey { get; set; }
        public string email { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string modulename { get; set; }
        public string rolename { get; set; }
        public Nullable<bool> isaccessible { get; set; }
        public System.DateTime auditinserteddatetime { get; set; }
        public Nullable<System.DateTime> auditupdateddatetime { get; set; }
        public Nullable<int> Rssd { get; set; }
        public Nullable<int> FDICNumber { get; set; }
    }
}
