//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactUBPRData
    {
        public int UBPRDataKey { get; set; }
        public int InstitutionKey { get; set; }
        public int UBPRDateKey { get; set; }
        public int UBPRConceptKey { get; set; }
        public int UBPRPeriodTypeKey { get; set; }
        public Nullable<decimal> UBPRDataValue { get; set; }
        public System.DateTime AuditInsertedDateTime { get; set; }
        public int AuditInsertedPackageKey { get; set; }
        public Nullable<System.DateTime> AuditUpdatedDateTime { get; set; }
        public Nullable<int> AuditUpdatedPackageKey { get; set; }
        public int UBPRReportingPeriodDateKey { get; set; }
    }
}
