//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactStdPGUBPRData
    {
        public long StdPGUBPRDataKey { get; set; }
        public int StdPeerGroupKey { get; set; }
        public int StdPGUBPRDateKey { get; set; }
        public int StdPGUBPRConceptKey { get; set; }
        public int StdPGUBPRPeriodTypeKey { get; set; }
        public Nullable<decimal> StdPGUBPRDataValue { get; set; }
        public System.DateTime AuditInsertedDateTime { get; set; }
        public int AuditInsertedPackageKey { get; set; }
        public Nullable<System.DateTime> AuditUpdatedDateTime { get; set; }
        public Nullable<int> AuditUpdatedPackageKey { get; set; }
    
        public virtual DimDate DimDate { get; set; }
        public virtual DimReportingPeriodType DimReportingPeriodType { get; set; }
        public virtual DimStdPeerGroup DimStdPeerGroup { get; set; }
        public virtual DimUBPRConcept DimUBPRConcept { get; set; }
    }
}
