//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactCustPGUBPRData
    {
        public long CustPGUBPRDataKey { get; set; }
        public int CustPeerGroupKey { get; set; }
        public int CustPGUBPRDateKey { get; set; }
        public int CustPGUBPRConceptKey { get; set; }
        public int CustPGUBPRPeriodTypeKey { get; set; }
        public Nullable<decimal> CustPGUBPRDataValue { get; set; }
        public System.DateTime AuditInsertedDateTime { get; set; }
        public Nullable<int> AuditInsertedPackageKey { get; set; }
        public Nullable<System.DateTime> AuditUpdatedDateTime { get; set; }
        public Nullable<int> AuditUpdatedPackageKey { get; set; }
    
        public virtual DimCustPeerGroup DimCustPeerGroup { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimReportingPeriodType DimReportingPeriodType { get; set; }
        public virtual DimUBPRConcept DimUBPRConcept { get; set; }
    }
}
