//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumConfig
    {
        public int ForumId { get; set; }
        public string ForumRegistrationURL { get; set; }
        public string ForumAuthenticationURL { get; set; }
        public string ForumHomeURL { get; set; }
    }
}
