//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KriMetricMaster
    {
        public int KriMetricId { get; set; }
        public string KriGroup { get; set; }
        public string MetricDesc { get; set; }
        public string Metric { get; set; }
        public string UBPRConceptCode { get; set; }
        public Nullable<int> IsDefault { get; set; }
        public Nullable<int> KriMetricSeq { get; set; }
        public Nullable<int> IsHighScoreGood { get; set; }
    }
}
