//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptCBRRiskRadarChartDetail
    {
        public long RptRiskRadarChartDetailsKey { get; set; }
        public string ReportTabName { get; set; }
        public Nullable<int> InstitutionKey { get; set; }
        public string CertNumber { get; set; }
        public string InstitutionName { get; set; }
        public string PeerGroupKey { get; set; }
        public string PeerGroup { get; set; }
        public string State { get; set; }
        public string Region { get; set; }
        public string AssetSize { get; set; }
        public Nullable<int> KriMetricId { get; set; }
        public Nullable<decimal> CurrentMinus4DataValue { get; set; }
        public Nullable<decimal> CurrentMinus3DataValue { get; set; }
        public Nullable<decimal> CurrentMinus2DataValue { get; set; }
        public Nullable<decimal> CurrentMinus1DataValue { get; set; }
        public Nullable<decimal> CurrentDataValue { get; set; }
        public Nullable<int> CurrentMinus4ScoreValue { get; set; }
        public Nullable<int> CurrentMinus3ScoreValue { get; set; }
        public Nullable<int> CurrentMinus2ScoreValue { get; set; }
        public Nullable<int> CurrentMinus1ScoreValue { get; set; }
        public Nullable<int> CurrentScoreValue { get; set; }
        public Nullable<int> IsHighScoreGood { get; set; }
        public Nullable<decimal> CurrentMinus4PeerGroupAvgValue { get; set; }
        public Nullable<decimal> CurrentMinus3PeerGroupAvgValue { get; set; }
        public Nullable<decimal> CurrentMinus2PeerGroupAvgValue { get; set; }
        public Nullable<decimal> CurrentMinus1PeerGroupAvgValue { get; set; }
        public Nullable<decimal> CurrentPeerGroupAvgValue { get; set; }
    }
}
