//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptCBRRiskRadarUserMetricmapping
    {
        public int UserMappingKey { get; set; }
        public Nullable<long> Userkey { get; set; }
        public Nullable<int> KRI1 { get; set; }
        public Nullable<int> KRI2 { get; set; }
        public Nullable<int> KRI3 { get; set; }
        public Nullable<int> KRI4 { get; set; }
        public Nullable<int> KRI5 { get; set; }
        public Nullable<int> KRI6 { get; set; }
        public Nullable<int> KRI7 { get; set; }
        public Nullable<int> KRI8 { get; set; }
        public Nullable<int> KRI9 { get; set; }
        public Nullable<int> KRI10 { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
