//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBR.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProjectNewDocCount
    {
        public string ProjectType { get; set; }
        public string DocumentType { get; set; }
        public string DocumentDisplayName { get; set; }
        public int NewDocCount { get; set; }
    }
}
