using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CBR.Web.Models
{
    public class StrategicForecastValueData
    {
        public Decimal? BankEquityCapitalPriorYear { get; set; }
        public Decimal? BankEquityCapitalCurrentQuarter { get; set; }
        public Decimal? BankEquityCapitalYear0 { get; set; }
        public Decimal? BankEquityCapitalYear1 { get; set; }
        public Decimal? BankEquityCapitalYear2 { get; set; }
        public Decimal? BankEquityCapitalYear3 { get; set; }
        public Decimal? BankEquityCapitalYear4 { get; set; }
        public Decimal? BankEquityCapitalYear5 { get; set; }
        public Decimal? ReturnOnAverageEquityPriorYear { get; set; }
        public Decimal? ReturnOnAverageEquityCurrentQuarter { get; set; }
        public Decimal? ReturnOnAverageEquityYear0 { get; set; }
        public Decimal? ReturnOnAverageEquityYear1 { get; set; }
        public Decimal? ReturnOnAverageEquityYear2 { get; set; }
        public Decimal? ReturnOnAverageEquityYear3 { get; set; }
        public Decimal? ReturnOnAverageEquityYear4 { get; set; }
        public Decimal? ReturnOnAverageEquityYear5 { get; set; }
        public Decimal? BookValueSharePricePriorYear { get; set; }
        public Decimal? BookValueSharePriceCurrentQuarter { get; set; }
        public Decimal? BookValueSharePriceYear0 { get; set; }
        public Decimal? BookValueSharePriceYear1 { get; set; }
        public Decimal? BookValueSharePriceYear2 { get; set; }
        public Decimal? BookValueSharePriceYear3 { get; set; }
        public Decimal? BookValueSharePriceYear4 { get; set; }
        public Decimal? BookValueSharePriceYear5 { get; set; }
        public Decimal? MarketValueSharePrice125Year0 { get; set; }
        public Decimal? MarketValueSharePrice125Year1 { get; set; }
        public Decimal? MarketValueSharePrice125Year2 { get; set; }
        public Decimal? MarketValueSharePrice125Year3 { get; set; }
        public Decimal? MarketValueSharePrice125Year4 { get; set; }
        public Decimal? MarketValueSharePrice125Year5 { get; set; }
        public Decimal? MarketValueSharePrice150Year0 { get; set; }
        public Decimal? MarketValueSharePrice150Year1 { get; set; }
        public Decimal? MarketValueSharePrice150Year2 { get; set; }
        public Decimal? MarketValueSharePrice150Year3 { get; set; }
        public Decimal? MarketValueSharePrice150Year4 { get; set; }
        public Decimal? MarketValueSharePrice150Year5 { get; set; }
        public Decimal? MarketValueSharePrice175Year0 { get; set; }
        public Decimal? MarketValueSharePrice175Year1 { get; set; }
        public Decimal? MarketValueSharePrice175Year2 { get; set; }
        public Decimal? MarketValueSharePrice175Year3 { get; set; }
        public Decimal? MarketValueSharePrice175Year4 { get; set; }
        public Decimal? MarketValueSharePrice175Year5 { get; set; }
        public Decimal? MarketValueSharePrice200Year0 { get; set; }
        public Decimal? MarketValueSharePrice200Year1 { get; set; }
        public Decimal? MarketValueSharePrice200Year2 { get; set; }
        public Decimal? MarketValueSharePrice200Year3 { get; set; }
        public Decimal? MarketValueSharePrice200Year4 { get; set; }
        public Decimal? MarketValueSharePrice200Year5 { get; set; }
        public Decimal? MarketValueSharePrice225Year0 { get; set; }
        public Decimal? MarketValueSharePrice225Year1 { get; set; }
        public Decimal? MarketValueSharePrice225Year2 { get; set; }
        public Decimal? MarketValueSharePrice225Year3 { get; set; }
        public Decimal? MarketValueSharePrice225Year4 { get; set; }
        public Decimal? MarketValueSharePrice225Year5 { get; set; }
        public Decimal? MarketValueSharePrice250Year0 { get; set; }
        public Decimal? MarketValueSharePrice250Year1 { get; set; }
        public Decimal? MarketValueSharePrice250Year2 { get; set; }
        public Decimal? MarketValueSharePrice250Year3 { get; set; }
        public Decimal? MarketValueSharePrice250Year4 { get; set; }
        public Decimal? MarketValueSharePrice250Year5 { get; set; }
        public Decimal? MarketValueSharePrice275Year0 { get; set; }
        public Decimal? MarketValueSharePrice275Year1 { get; set; }
        public Decimal? MarketValueSharePrice275Year2 { get; set; }
        public Decimal? MarketValueSharePrice275Year3 { get; set; }
        public Decimal? MarketValueSharePrice275Year4 { get; set; }
        public Decimal? MarketValueSharePrice275Year5 { get; set; }
        public Decimal? MarketValueSharePrice300Year0 { get; set; }
        public Decimal? MarketValueSharePrice300Year1 { get; set; }
        public Decimal? MarketValueSharePrice300Year2 { get; set; }
        public Decimal? MarketValueSharePrice300Year3 { get; set; }
        public Decimal? MarketValueSharePrice300Year4 { get; set; }
        public Decimal? MarketValueSharePrice300Year5 { get; set; }
        public Decimal? AssetGrowthRatePriorYear { get; set; }
        public Decimal? AssetGrowthRateCurrentQuarter { get; set; }
        public Decimal? AssetGrowthRateYear0 { get; set; }
        public Decimal? AssetGrowthRateYear1 { get; set; }
        public Decimal? AssetGrowthRateYear2 { get; set; }
        public Decimal? AssetGrowthRateYear3 { get; set; }
        public Decimal? AssetGrowthRateYear4 { get; set; }
        public Decimal? AssetGrowthRateYear5 { get; set; }
        public Decimal? NetIncomePriorYear { get; set; }
        public Decimal? NetIncomeCurrentQuarter { get; set; }
        public Decimal? NetIncomeYear0 { get; set; }
        public Decimal? NetIncomeYear1 { get; set; }
        public Decimal? NetIncomeYear2 { get; set; }
        public Decimal? NetIncomeYear3 { get; set; }
        public Decimal? NetIncomeYear4 { get; set; }
        public Decimal? NetIncomeYear5 { get; set; }
        public Decimal? ReturnOnAverageAssetsPriorYear { get; set; }
        public Decimal? ReturnOnAverageAssetsCurrentQuarter { get; set; }
        public Decimal? ReturnOnAverageAssetsYear0 { get; set; }
        public Decimal? ReturnOnAverageAssetsYear1 { get; set; }
        public Decimal? ReturnOnAverageAssetsYear2 { get; set; }
        public Decimal? ReturnOnAverageAssetsYear3 { get; set; }
        public Decimal? ReturnOnAverageAssetsYear4 { get; set; }
        public Decimal? ReturnOnAverageAssetsYear5 { get; set; }
        public Decimal? DividendsPriorYear { get; set; }
        public Decimal? DividendsCurrentQuarter { get; set; }
        public Decimal? DividendsYear0 { get; set; }
        public Decimal? DividendsYear1 { get; set; }
        public Decimal? DividendsYear2 { get; set; }
        public Decimal? DividendsYear3 { get; set; }
        public Decimal? DividendsYear4 { get; set; }
        public Decimal? DividendsYear5 { get; set; }
        public Decimal? DividendsRatePriorYear { get; set; }
        public Decimal? DividendsRateCurrentQuarter { get; set; }
        public Decimal? DividendsRateYear0 { get; set; }
        public Decimal? DividendsRateYear1 { get; set; }
        public Decimal? DividendsRateYear2 { get; set; }
        public Decimal? DividendsRateYear3 { get; set; }
        public Decimal? DividendsRateYear4 { get; set; }
        public Decimal? DividendsRateYear5 { get; set; }
        public Decimal? NewCapitalPriorYear { get; set; }
        public Decimal? NewCapitalCurrentQuarter { get; set; }
        public Decimal? NewCapitalYear0 { get; set; }
        public Decimal? NewCapitalYear1 { get; set; }
        public Decimal? NewCapitalYear2 { get; set; }
        public Decimal? NewCapitalYear3 { get; set; }
        public Decimal? NewCapitalYear4 { get; set; }
        public Decimal? NewCapitalYear5 { get; set; }
        public Decimal? PricePerSharePriorYear { get; set; }
        public Decimal? PricePerShareCurrentQuarter { get; set; }
        public Decimal? PricePerShareYear0 { get; set; }
        public Decimal? PricePerShareYear1 { get; set; }
        public Decimal? PricePerShareYear2 { get; set; }
        public Decimal? PricePerShareYear3 { get; set; }
        public Decimal? PricePerShareYear4 { get; set; }
        public Decimal? PricePerShareYear5 { get; set; }
        public Decimal? NewAcquisitionAssetsPriorYear { get; set; }
        public Decimal? NewAcquisitionAssetsCurrentQuarter { get; set; }
        public Decimal? NewAcquisitionAssetsYear0 { get; set; }
        public Decimal? NewAcquisitionAssetsYear1 { get; set; }
        public Decimal? NewAcquisitionAssetsYear2 { get; set; }
        public Decimal? NewAcquisitionAssetsYear3 { get; set; }
        public Decimal? NewAcquisitionAssetsYear4 { get; set; }
        public Decimal? NewAcquisitionAssetsYear5 { get; set; }
        public Decimal? Cet1CapitalAdjustmentPriorYear { get; set; }
        public Decimal? Cet1CapitalAdjustmentCurrentQuarter { get; set; }
        public Decimal? Cet1CapitalAdjustmentYear0 { get; set; }
        public Decimal? Cet1CapitalAdjustmentYear1 { get; set; }
        public Decimal? Cet1CapitalAdjustmentYear2 { get; set; }
        public Decimal? Cet1CapitalAdjustmentYear3 { get; set; }
        public Decimal? Cet1CapitalAdjustmentYear4 { get; set; }
        public Decimal? Cet1CapitalAdjustmentYear5 { get; set; }
        public Decimal? Tier1CapitalAdjustmentPriorYear { get; set; }
        public Decimal? Tier1CapitalAdjustmentCurrentQuarter { get; set; }
        public Decimal? Tier1CapitalAdjustmentYear0 { get; set; }
        public Decimal? Tier1CapitalAdjustmentYear1 { get; set; }
        public Decimal? Tier1CapitalAdjustmentYear2 { get; set; }
        public Decimal? Tier1CapitalAdjustmentYear3 { get; set; }
        public Decimal? Tier1CapitalAdjustmentYear4 { get; set; }
        public Decimal? Tier1CapitalAdjustmentYear5 { get; set; }
        public Decimal? Tier2CapitalPriorYear { get; set; }
        public Decimal? Tier2CapitalCurrentQuarter { get; set; }
        public Decimal? Tier2CapitalYear0 { get; set; }
        public Decimal? Tier2CapitalYear1 { get; set; }
        public Decimal? Tier2CapitalYear2 { get; set; }
        public Decimal? Tier2CapitalYear3 { get; set; }
        public Decimal? Tier2CapitalYear4 { get; set; }
        public Decimal? Tier2CapitalYear5 { get; set; }
        public Decimal? RiskWeightedAssetsPriorYear { get; set; }
        public Decimal? RiskWeightedAssetsCurrentQuarter { get; set; }
        public Decimal? RiskWeightedAssetsYear0 { get; set; }
        public Decimal? RiskWeightedAssetsYear1 { get; set; }
        public Decimal? RiskWeightedAssetsYear2 { get; set; }
        public Decimal? RiskWeightedAssetsYear3 { get; set; }
        public Decimal? RiskWeightedAssetsYear4 { get; set; }
        public Decimal? RiskWeightedAssetsYear5 { get; set; }
        public Decimal? TotalAssetsForLeveragePriorYear { get; set; }
        public Decimal? TotalAssetsForLeverageCurrentQuarter { get; set; }
        public Decimal? TotalAssetsForLeverageYear0 { get; set; }
        public Decimal? TotalAssetsForLeverageYear1 { get; set; }
        public Decimal? TotalAssetsForLeverageYear2 { get; set; }
        public Decimal? TotalAssetsForLeverageYear3 { get; set; }
        public Decimal? TotalAssetsForLeverageYear4 { get; set; }
        public Decimal? TotalAssetsForLeverageYear5 { get; set; }
        public Decimal? SharesOutstandingPriorYear { get; set; }
        public Decimal? SharesOutstandingCurrentQuarter { get; set; }
        public Decimal? SharesOutstandingYear0 { get; set; }
        public Decimal? SharesOutstandingYear1 { get; set; }
        public Decimal? SharesOutstandingYear2 { get; set; }
        public Decimal? SharesOutstandingYear3 { get; set; }
        public Decimal? SharesOutstandingYear4 { get; set; }
        public Decimal? SharesOutstandingYear5 { get; set; }
        public Decimal? Tier2CapitalToTier1PriorYear { get; set; }
        public Decimal? Tier2CapitalToTier1CurrentQuarter { get; set; }
        public Decimal? RiskWeightedAssetsToAssetsPriorYear { get; set; }
        public Decimal? RiskWeightedAssetsToAssetsCurrentQuarter { get; set; }
        public Decimal? AssetsForLeverageToAssetsPriorYear { get; set; }
        public Decimal? AssetsForLeverageToAssetsCurrentQuarter { get; set; }
        public Decimal? TotalAssetsYear0 { get; set; }
        public Decimal? TotalAssetsYear1 { get; set; }
        public Decimal? TotalAssetsYear2 { get; set; }
        public Decimal? TotalAssetsYear3 { get; set; }
        public Decimal? TotalAssetsYear4 { get; set; }
        public Decimal? TotalAssetsYear5 { get; set; }

        // missing newly added properties
        public Decimal? Cet1CapitalPriorYear { get; set; }
        public Decimal? Cet1CapitalCurrentQuarter { get; set; }
        public Decimal? Tier1CapitalPriorYear { get; set; }
        public Decimal? Tier1CapitalCurrentQuarter { get; set; }
        public Decimal? TotalRiskBasedCapitalPriorYear { get; set; }
        public Decimal? TotalRiskBasedCapitalCurrentQuarter { get; set; }
        public Decimal? TotalAssetsPriorYear { get; set; }
        public Decimal? TotalAssetsCurrentQuarter { get; set; }
        public Decimal? Cet1CapitalRatioPriorYear { get; set; }
        public Decimal? Cet1CapitalRatioCurrentQuarter { get; set; }
        public Decimal? Tier1RBCRatioPriorYear { get; set; }
        public Decimal? Tier1RBCRatioCurrentQuarter { get; set; }
        public Decimal? TotalRBCRatioPriorYear { get; set; }
        public Decimal? TotalRBCRatioCurrentQuarter { get; set; }
        public Decimal? Tier1LeverageRatioPriorYear { get; set; }
        public Decimal? Tier1LeverageRatioCurrentQuarter { get; set; }

        //newly added properties
        public Decimal? MarketValueSharePrice125PriorYear { get; set; }
        public Decimal? MarketValueSharePrice125CurrentQuarter { get; set; }
        public Decimal? MarketValueSharePrice150PriorYear { get; set; }
        public Decimal? MarketValueSharePrice150CurrentQuarter { get; set; }
        public Decimal? MarketValueSharePrice175PriorYear { get; set; }
        public Decimal? MarketValueSharePrice175CurrentQuarter { get; set; }
        public Decimal? MarketValueSharePrice200PriorYear { get; set; }
        public Decimal? MarketValueSharePrice200CurrentQuarter { get; set; }
        public Decimal? MarketValueSharePrice225PriorYear { get; set; }
        public Decimal? MarketValueSharePrice225CurrentQuarter { get; set; }
        public Decimal? MarketValueSharePrice250PriorYear { get; set; }
        public Decimal? MarketValueSharePrice250CurrentQuarter { get; set; }
        public Decimal? MarketValueSharePrice275PriorYear { get; set; }
        public Decimal? MarketValueSharePrice275CurrentQuarter { get; set; }
        public Decimal? MarketValueSharePrice300PriorYear { get; set; }
        public Decimal? MarketValueSharePrice300CurrentQuarter { get; set; }
    }
}
